on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - uses: microsoft/setup-msbuild@v2

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m debug -p windows -v -y

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-x64-debug-${{ github.sha }}
          path: |
            bin/

      # SDK相关任务
      - name: Create SDK directories
        run: |
          mkdir SDK
          mkdir SDK/lib
          mkdir SDK/include

      - name: Copy include files to SDK
        run: |
          Copy-Item -Path include/* -Destination SDK/include/ -Recurse -Force
        shell: pwsh

      - name: Copy .lib files to SDK/lib
        run: |
          New-Item -Path SDK/lib -ItemType Directory -Force
          Copy-Item -Path build/windows/x64/release/*.lib -Destination SDK/lib/ -Force
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: SDK-${{ github.sha }}
          path: SDK

  # clang-format:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - run: |
  #         choco install llvm -y --version=17.0.6

  #     - name: clang-format
  #       run: |
  #         Get-ChildItem src/ -Filter *.cpp -Recurse | ForEach-Object { clang-format --dry-run -Werror $_.FullName; if ($LASTEXITCODE -ne 0) { exit 1; } }
  #         Get-ChildItem src/ -Filter *.h -Recurse | ForEach-Object { clang-format --dry-run -Werror $_.FullName; if ($LASTEXITCODE -ne 0) { exit 1; } }
