on:
  pull_request:
    paths:
      - src/**
      - include/**
      - xmake.lua
      - .github/workflows/build.yml
  push:
    paths:
      - src/**
      - include/**
      - xmake.lua
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  build:
    env:
      targetName: ${{ matrix.overworld == 'y' && 'overworld' || 'more_dimension' }}
    strategy:
      matrix:
        overworld: ["y", "n"]
    name: Build-${{ matrix.overworld == 'y' && 'overworld' || 'more_dimension' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1
        # with:
        #   xmake-version: "2.9.3"

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      # - uses: microsoft/setup-msbuild@v2

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ env.targetName }}-${{ github.sha }}
          path: |
            bin/

      # SDK相关任务
      - name: Create SDK directories
        run: |
          mkdir SDK
          mkdir SDK/lib
          mkdir SDK/include

      - name: Copy include files to SDK
        run: |
          Copy-Item -Path include/* -Destination SDK/include/ -Recurse -Force
        shell: pwsh

      - name: Copy .lib files to SDK/lib
        run: |
          New-Item -Path SDK/lib -ItemType Directory -Force
          Copy-Item -Path build/windows/x64/release/*.lib -Destination SDK/lib/ -Force
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: SDK-${{ env.targetName }}-${{ github.sha }}
          path: SDK
